export const paths = {
  home: '/',
  auth: { signIn: '/auth/sign-in', signUp: '/auth/sign-up', resetPassword: '/auth/reset-password' },
  dashboard: {
    overview: '/dashboard',
    account: '/dashboard/account',
    customers: '/dashboard/customers',
    integrations: '/dashboard/integrations',
    perfumes: '/dashboard/perfumes',
    requests: '/dashboard/requests',
    gallery: '/dashboard/gallery',
    posts: '/dashboard/posts',
    brands: '/dashboard/brands',
    notes: '/dashboard/notes',
    news: '/dashboard/news',
    comments: '/dashboard/reviews',
    newscomments: '/dashboard/news-comments',
    articlecomments: '/dashboard/article-comments',
    parfumers: '/dashboard/parfumers',
    users: '/dashboard/users',
    settings: '/dashboard/settings',
  },
  errors: { notFound: '/errors/not-found' },
} as const;
